import sys, os
sys.path.insert(0, os.path.abspath('.'))

from database.db_manager import save_factor_metadata_batch

HARDCODED_DESCRIPTIONS = {
    'funding_rate': ('BTC_USDT', 'Binance BTC 永续合约资金费率', 'Binance', '', ''),
    'mvrv': ('BTC_USDT', 'CoinMetrics BTC MVRV 市值/已实现价值比率', 'CoinMetrics', '', ''),
    'btc_whale_hoarding_ratio': ('BTC_USDT', 'CoinMetrics BTC 1年未活跃供应占比（鲸鱼囤币指标）', 'CoinMetrics', '', ''),
    'fear_greed': ('BTC_USDT', 'Alternative.me 恐惧与贪婪指数', 'Alternative.me', '', ''),
    'btc_dvol': ('BTC_USDT', 'Deribit DVOL 比特币隐含波动率指数', 'Deribit', '', ''),
    'stablecoin_flow_7d': ('BTC_USDT', 'DefiLlama 稳定币总市值 7 日变化率', 'DefiLlama', '', ''),
    'chain_tvl': ('GLOBAL', 'DefiLlama 各链 TVL', 'DefiLlama', '', ''),
    'daily_fees_usd': ('GLOBAL', 'DefiLlama 协议日费用收入', 'DefiLlama', '', ''),
    'dex_daily_volume_usd': ('GLOBAL', 'DefiLlama DEX 日交易量', 'DefiLlama', '', ''),
    'defi_stablecoin_apy': ('GLOBAL', 'DefiLlama 稳定币借贷收益率', 'DefiLlama', '', ''),
    'btc_dominance': ('GLOBAL', 'CoinGecko BTC 市值占比', 'CoinGecko', '', ''),
    'public_company_btc_holdings': ('GLOBAL', 'CoinGecko 上市公司 BTC 持仓', 'CoinGecko', '', ''),
    'ai_sector_total_market_cap': ('AI_SECTOR_INDEX', 'CoinGecko AI 板块总市值', 'CoinGecko', '', ''),
    'lst_peg_ratio': ('GLOBAL', 'CoinGecko LST 锚定偏差率', 'CoinGecko', '', ''),
    'open_interest': ('BTC_USDT', 'Binance BTC 期货持仓量', 'Binance', '', ''),
    'binance_funding_rate': ('BTC_USDT', 'Binance BTC 资金费率', 'Binance', '', ''),
    'bybit_funding_rate': ('BTC_USDT', 'Bybit BTC 资金费率', 'Bybit', '', ''),
    'buyback_blackout_ratio': ('SPY', '美股回购静默期比例（标的指数成分股中处于财报前回购禁令期的占比）', 'FMP', '', ''),
    'top10_quarterly_buyback_amount': ('MACRO', '美股 Top10 回购公司季度回购金额合计', 'FMP', '', ''),
    'etf_fiat_volume': ('MACRO', 'ETF 法币交易量', 'FMP', '', ''),
    'crude_term_spread': ('MACRO', '布伦特原油期限价差（近月-远月）/近月，正值=Backwardation，负值=Contango', 'EIA', '', ''),
    'btc_fiat_premium': ('BTC_USDT', 'BTC 法币溢价指数（韩国/土耳其等法币市场 BTC 价格 vs USD 市场价格的偏离度）', 'CoinGecko', '', ''),
    'gold_cb_buy_residual': ('MACRO', '黄金央行买盘残差（全球央行黄金净购买量扣除趋势项后的异常值，正值=央行超常增持）', 'WGC', '', ''),
    'dgs10': ('MACRO', '10年期美国国债收益率', 'FRED', '%', ''),
    'dgs2': ('MACRO', '2年期美国国债收益率', 'FRED', '%', ''),
    'dgs5': ('MACRO', '5年期美国国债收益率', 'FRED', '%', ''),
    'dgs30': ('MACRO', '30年期美国国债收益率', 'FRED', '%', ''),
    'dgs1': ('MACRO', '1年期美国国债收益率', 'FRED', '%', ''),
    't10y2y': ('MACRO', '10年-2年国债利差（收益率曲线斜率）', 'FRED', '%', ''),
    't10y3m': ('MACRO', '10年-3月国债利差', 'FRED', '%', ''),
    't10yie': ('MACRO', '10年期盈亏平衡通胀率', 'FRED', '%', ''),
    't5yie': ('MACRO', '5年期盈亏平衡通胀率', 'FRED', '%', ''),
    't5yifr': ('MACRO', '5年5年远期通胀率', 'FRED', '%', ''),
    'dff': ('MACRO', '联邦基金有效利率', 'FRED', '%', ''),
    'fedfunds': ('MACRO', '联邦基金利率', 'FRED', '%', ''),
    'dfii10': ('MACRO', '10年期TIPS实际收益率', 'FRED', '%', ''),
    'dfii5': ('MACRO', '5年期TIPS实际收益率', 'FRED', '%', ''),
    'tb3ms': ('MACRO', '3月期国库券二级市场利率', 'FRED', '%', ''),
    'cpiaucsl': ('MACRO', 'CPI 所有城市消费者（季调）', 'FRED', '', 'M'),
    'cpiaucns': ('MACRO', 'CPI 所有城市消费者（非季调）', 'FRED', '', 'M'),
    'cpilfesl': ('MACRO', '核心CPI（剔除食品能源）', 'FRED', '', 'M'),
    'cpimedns': ('MACRO', '中位数CPI', 'FRED', '', 'M'),
    'corestickm159sfrbatl': ('MACRO', '粘性核心CPI（亚特兰大联储）', 'FRED', '', 'M'),
    'pce': ('MACRO', 'PCE 物价指数', 'FRED', '', 'M'),
    'pcepi': ('MACRO', 'PCE 物价指数（非季调）', 'FRED', '', 'M'),
    'pcepilfe': ('MACRO', '核心PCE物价指数', 'FRED', '', 'M'),
    'dpccrv1q225sbea': ('MACRO', 'PCE 价格指数季环比年化', 'FRED', '', 'Q'),
    'gdp': ('MACRO', '名义GDP', 'FRED', '', 'Q'),
    'gdpc1': ('MACRO', '实际GDP', 'FRED', '', 'Q'),
    'gdpdef': ('MACRO', 'GDP平减指数', 'FRED', '', 'Q'),
    'gdpnow': ('MACRO', '亚特兰大联储 GDPNow 预测', 'FRED', '', 'Q'),
    'indpro': ('MACRO', '工业生产指数', 'FRED', '', 'M'),
    'unrate': ('MACRO', '失业率', 'FRED', '%', 'M'),
    'payems': ('MACRO', '非农就业人数', 'FRED', '', 'M'),
    'civpart': ('MACRO', '劳动参与率', 'FRED', '%', 'M'),
    'manemp': ('MACRO', '制造业就业人数', 'FRED', '', 'M'),
    'icsa': ('MACRO', '初请失业金人数', 'FRED', '', 'W'),
    'houst': ('MACRO', '新屋开工数', 'FRED', '', 'M'),
    'm1sl': ('MACRO', 'M1 货币供应量', 'FRED', '', 'M'),
    'm2sl': ('MACRO', 'M2 货币供应量', 'FRED', '', 'M'),
    'walcl': ('MACRO', '美联储总资产', 'FRED', '', 'W'),
    'wresbal': ('MACRO', '美联储准备金余额', 'FRED', '', 'W'),
    'gfdebtn': ('MACRO', '联邦债务总额', 'FRED', '', 'Q'),
    'gfdegdq188s': ('MACRO', '联邦债务占GDP比重', 'FRED', '%', 'Q'),
    'umcsent': ('MACRO', '密歇根大学消费者信心指数', 'FRED', '', 'M'),
    'nfci': ('MACRO', '芝加哥联储全国金融状况指数', 'FRED', '', 'W'),
    'stlfsi4': ('MACRO', '圣路易斯联储金融压力指数', 'FRED', '', 'W'),
    'sahmrealtime': ('MACRO', 'Sahm规则衰退指标（实时）', 'FRED', '%', 'M'),
    'vixcls': ('MACRO', 'VIX 波动率指数', 'FRED', '', 'D'),
    'gvzcls': ('MACRO', '黄金波动率指数', 'FRED', '', 'D'),
    'dcoilbrenteu': ('MACRO', '布伦特原油现货价格', 'FRED', '$', 'D'),
    'dcoilwtico': ('MACRO', 'WTI原油现货价格', 'FRED', '$', 'D'),
    'dexuseu': ('MACRO', '美元/欧元汇率', 'FRED', '', 'D'),
    'dexjpus': ('MACRO', '美元/日元汇率', 'FRED', '', 'D'),
    'dtwexbgs': ('MACRO', '美元贸易加权指数', 'FRED', '', 'D'),
    'sp500': ('MACRO', 'S&P 500 指数', 'FRED', '', 'D'),
    'nasdaqcom': ('MACRO', '纳斯达克综合指数', 'FRED', '', 'D'),
    'nasdaq100': ('MACRO', '纳斯达克100指数', 'FRED', '', 'D'),
    'djia': ('MACRO', '道琼斯工业平均指数', 'FRED', '', 'D'),
    'gasregw': ('MACRO', '美国常规汽油零售价格', 'FRED', '$', 'W'),
    'wtisplc': ('MACRO', 'WTI 原油现货价格（FRED）', 'FRED', '$', 'M'),
    'mortgage30us': ('MACRO', '30年期固定利率抵押贷款利率', 'FRED', '%', 'W'),
    'sofr': ('MACRO', '担保隔夜融资利率', 'FRED', '%', 'D'),
    'bamlc0a0cm': ('MACRO', '美国公司债总回报指数期权调整利差', 'FRED', '%', 'D'),
    'bamlh0a0hym2': ('MACRO', '美国高收益债利差', 'FRED', '%', 'D'),
    'bamlh0a1hybb': ('MACRO', '美国高收益率债利差（BB级）', 'FRED', '%', 'D'),
    'bamlc0a4cbbb': ('MACRO', '美国投资级公司债利差（BBB级）', 'FRED', '%', 'D'),
    'bamlhe00ehyioas': ('MACRO', '欧洲高收益债利差', 'FRED', '%', 'D'),
    'bamlc0a4cbbbey': ('MACRO', 'BBB级公司债有效收益率', 'FRED', '%', 'D'),
    'bamlh0a0hym2ey': ('MACRO', '高收益债有效收益率', 'FRED', '%', 'D'),
    'bamlh0a3hyc': ('MACRO', 'CCC级高收益债利差', 'FRED', '%', 'D'),
    'bamlh0a3hycey': ('MACRO', 'CCC级高收益债有效收益率', 'FRED', '%', 'D'),
    'emvmacrobroad': ('MACRO', '宏观经济新闻情绪指数（广义）', 'FRED', '', 'D'),
    'emvmacrobus': ('MACRO', '宏观经济新闻情绪指数（商业）', 'FRED', '', 'D'),
    'emvmacroconsume': ('MACRO', '宏观经济新闻情绪指数（消费）', 'FRED', '', 'D'),
    'emvmacrofinind': ('MACRO', '宏观经济新闻情绪指数（金融工业）', 'FRED', '', 'D'),
    'emvmacroinflation': ('MACRO', '宏观经济新闻情绪指数（通胀）', 'FRED', '', 'D'),
    'emvmacrointerest': ('MACRO', '宏观经济新闻情绪指数（利率）', 'FRED', '', 'D'),
    'emvmacrolabormkt': ('MACRO', '宏观经济新闻情绪指数（劳动力市场）', 'FRED', '', 'D'),
    'emvmacronews': ('MACRO', '宏观经济新闻情绪指数（新闻）', 'FRED', '', 'D'),
    'emvmacrore': ('MACRO', '宏观经济新闻情绪指数（房地产）', 'FRED', '', 'D'),
    'emvmacrotrade': ('MACRO', '宏观经济新闻情绪指数（贸易）', 'FRED', '', 'D'),
    'usepuindxd': ('MACRO', '经济政策不确定性指数', 'FRED', '', 'D'),
    'jlnum1m': ('MACRO', '1个月跳跃风险指数', 'FRED', '', 'M'),
    'jlnum3m': ('MACRO', '3个月跳跃风险指数', 'FRED', '', 'M'),
    'jlnum12m': ('MACRO', '12个月跳跃风险指数', 'FRED', '', 'M'),
    'rrpontsyd': ('MACRO', '回购利率', 'FRED', '%', 'D'),
    'qder628bis': ('MACRO', 'BIS 有效汇率', 'FRED', '', 'M'),
    'drsfrmacbs': ('MACRO', '美联储贴现率', 'FRED', '%', 'M'),
    'dfedtaru': ('MACRO', '联邦基金目标利率上限', 'FRED', '%', 'D'),
    'obmmiva30yf': ('MACRO', '30年期VA抵押贷款利率', 'FRED', '%', 'W'),
    'pcu325211325211': ('MACRO', 'PPI: 制药工业', 'FRED', '', 'M'),
    'fpcpitotlzgusa': ('MACRO', 'IMF CPI总指数（美国）', 'FRED', '', 'M'),
    'bopgstb': ('MACRO', '国际收支: 商品贸易余额', 'FRED', '', 'Q'),
    'apu0000703112': ('MACRO', 'BLS CPI: 医疗保健', 'FRED', '', 'M'),
    'apu0000708111': ('MACRO', 'BLS CPI: 个人电脑', 'FRED', '', 'M'),
    'apu0000709112': ('MACRO', 'BLS CPI: 有线电视', 'FRED', '', 'M'),
    'apu000072610': ('MACRO', 'BLS CPI: 电力', 'FRED', '', 'M'),
    'apu000074714': ('MACRO', 'BLS CPI: 电话服务', 'FRED', '', 'M'),
    'csushpinsa': ('MACRO', 'Case-Shiller 全国房价指数（非季调）', 'FRED', '', 'M'),
    'csushpisa': ('MACRO', 'Case-Shiller 全国房价指数（季调）', 'FRED', '', 'M'),
    'cusr0000seta02': ('MACRO', 'CPI: 住宅', 'FRED', '', 'M'),
    'cuur0000sa0r': ('MACRO', 'CPI: 所有项目（非季调）', 'FRED', '', 'M'),
    'les1252881600q': ('MACRO', '就业成本指数', 'FRED', '', 'Q'),
    'mehoinusa672n': ('MACRO', '中等家庭收入', 'FRED', '', 'A'),
    'mspus': ('MACRO', '新房中位价', 'FRED', '$', 'Q'),
    'myagm2cnm189n': ('MACRO', 'M2 货币供应（成分）', 'FRED', '', 'M'),
    'myagm2ezm196n': ('MACRO', 'M2 货币供应（成分）', 'FRED', '', 'M'),
    'myagm2jpm189n': ('MACRO', 'M2 货币供应（成分）', 'FRED', '', 'M'),
    'ihlidxus': ('MACRO', '美联储金融压力指数', 'FRED', '', 'W'),
    'ihlidxustpsoftdeve': ('MACRO', '金融压力指数（软开发）', 'FRED', '', 'W'),
    'stleni': ('MACRO', '圣路易斯金融压力指数', 'FRED', '', 'W'),
    'recprousm156n': ('MACRO', '衰退概率', 'FRED', '%', 'M'),
    'sipovginiusa': ('MACRO', '基尼系数（美国）', 'FRED', '', 'A'),
    'ussthpi': ('MACRO', '州房价指数', 'FRED', '', 'Q'),
    'wtregen': ('MACRO', '风能发电量', 'FRED', '', 'M'),
}

metadata_list = []
for fn, (symbol, desc, source, unit, freq) in HARDCODED_DESCRIPTIONS.items():
    metadata_list.append({
        'factor_name': fn,
        'symbol': symbol,
        'description': desc,
        'source': source,
        'unit': unit,
        'update_freq': freq,
    })

save_factor_metadata_batch(metadata_list)
print(f"已迁移 {len(metadata_list)} 条因子描述到 factor_metadata 表")
